### ISSUE TITLE
Changing background color of ktd-grid-item

### ISSUE THREAD

**Issue by omeragictarik** [katoid/angular-grid-layout#10]
Hi. I'm trying to change background color of a grid item and cannot find a solution how to do it, even with ng-deep. Is there a way to change the color of a grid item? Thanks

**Comment by llorenspujol** [comment]
Hi @omeragictarik ,

The element `ktd-grid-item` has no background. The background is on the content you project inside. Therefore you just need to project the content with you desired styling, take for example this [stackblitz](https://stackblitz.com/edit/angular-grid-layout-playground-green-background?file=src/app/playground/playground.component.html) (where I put a default green background and if the grid item is odd I override it with a red background).
