### ISSUE TITLE
Dragging and Resizing not working on windows touch screen

### ISSUE THREAD

**Issue by NgaiKaKit** [katoid/angular-grid-layout#105]
As title, Dragging and Resizing are not functional on Windows touch screen, device such as "Surface pro" / windows laptop support touch screen.

Open the Playground by Chrome / Edge on those devices can reproduce the issue.

https://katoid.github.io/angular-grid-layout/playground

**Comment by Duckelekuuk** [comment]
Fixed in this [PR](https://github.com/katoid/angular-grid-layout/pull/90)
