### ISSUE TITLE
BUG(demo-app): Drag and resize in custom handles example does not work well, it gets interrupted by the default browser drag action. 

### ISSUE THREAD

**Issue by llorenspujol** [katoid/angular-grid-layout#120]
### How to reproduce?

Open the custom-handles [example](https://katoid.github.io/angular-grid-layout/custom-handles) and drag or resize and item.

### Video of the bug:

![62dbdeb2e3a058132f5aa0f6da88223f](https://github.com/katoid/angular-grid-layout/assets/18361241/db82de0e-3548-46cd-85ef-3bdc8cfc05f7)

**Comment by manolumjm** [comment]
Fix in https://github.com/katoid/angular-grid-layout/pull/122
