### ISSUE TITLE
Feature: add preventCollision flag 

### ISSUE THREAD

**Issue by jakubbialas** [katoid/angular-grid-layout#14]
In react-grid-layout there is preventCollision flag, which prevents layout from getting messed up in no compaction mode.
I would love to have this feature in there, I already made an implementation of it (it uses code from react-grid-layout which was already there).

**Comment by llorenspujol** [comment]
Yes, this feature makes lot of sense and I agree it needs to be added. The pull request is nice but there is one use case that needs some discussion. I commented it on the pull request: https://github.com/katoid/angular-grid-layout/pull/15#issuecomment-865692530
