### ISSUE TITLE
Is it possible to use it in Angular 12?

### ISSUE THREAD

**Issue by GDenizKaratas** [katoid/angular-grid-layout#19]
I loved your work. But I couldn't make it work in Angular 12. Is it possible to use it in 12?

**Comment by llorenspujol** [comment]
Thanks!
What are the errors you are facing using it in Angular v12? It is not officially supported but it should work.
A version supporting officially Angular v12 should come briefly. 

If you need it now, you can make a merge request upgrading this library to Angular v12. It should not require much changes.

**Comment by GDenizKaratas** [comment]
Thanks for the answer :)

**Comment by ScottSpittle** [comment]
I've got it working just fine using Angular 12

**Comment by ScottSpittle** [comment]
> > I've got it working just fine using Angular 12
> 
> Any changes u made?

No changes, just installed it and followed the usage documentation

**Comment by llorenspujol** [comment]
Closing this issue, versions >= 1.1.0 officially support Angular v12
