### ISSUE TITLE
Request to Add an API to print the whole Grid. 

### ISSUE THREAD

**Issue by SamanThind** [katoid/angular-grid-layout#22]
Please provide an API to print the grid on a page. Can be used in various scenarios like in label design and printing.

**Comment by llorenspujol** [comment]
I may missing something, but if it is the 'print' I am thinking, the grid doesn't have to be responsible of that. You can do something like: https://stackoverflow.com/a/2255438/6099651 without the grid handling it.

If this link doesn't solve your issue, can you detail more your use case?

**Comment by SamanThind** [comment]
We are using this layout for making custom UCC labels. We have find most of the work done but we are stuck at one place that we want to print multiple prints of a grid at one time with different value ( like around 100 prints in one transaction ) we cant click on every single click so we want a shortcut that we can call a print function which can create a print html for us  . If you already have something like this or some other way u have n mind please let me know.

**Comment by llorenspujol** [comment]
This kind of functionality is out fo scope right now. As far as I understand your issue, is not the responsibility of the grid to 'print'. You can make a task or something over the grid that changes automatically the grid value and prints for each one result. So, you can automate the content you set to the grid, the grid is not responsible of that, it is just responsible for the layout positioning.

Said that, I close the issue, if you need help, you can reach me personally and I will try to help if I can.
