### ISSUE TITLE
Is it possible to use in Angular 7?

### ISSUE THREAD

**Issue by seidme** [katoid/angular-grid-layout#29]
First of all great work, made my day when I stumbled upon this repo!

I'm trying to use it in Angular 7, but when I import KtdGridModule it throws the following error: 
![image](https://user-images.githubusercontent.com/12798750/150051637-b5e57149-f55d-4138-83b3-ad9381672d6e.png)

I suppose it's some versioning issue, any idea?

Thanks ^^

**Comment by llorenspujol** [comment]
Angular 7 is not supported. 

The minor Angular version you can use with @katoid/angular-grid-layout@0.2.0 is Angular 9. But, this is an 'unofficial' support.
@katoid/angular-grid-layout@0.2.0 is build in angular@^11.0.0, so the angular application that consumes it should preferably use an angular version >= 11.0.0.

I suggest you upgrade your angular version to 11 or greater. If this is impossible, you can fork this project and downgrade Angular to version 7.
