### ISSUE TITLE
bug(demo-app-playgound): Mobile --> `isDragging` chip does not change color while dragging 

### ISSUE THREAD

**Issue by Achilles1515** [katoid/angular-grid-layout#3]
Title pretty much says it all.

~~Not sure if this is just iOS or specific to iOS 14 - haven't dug into any of the code yet.~~
EDIT: Is reproducible with Chrome simulating a mobile device.

Video demonstration:
![GIF](https://user-images.githubusercontent.com/23387905/106847220-77fd5100-667c-11eb-914e-c735c00d9554.gif)

**Comment by llorenspujol** [comment]
Thanks for the report! It also happens in my Android phone, I am quite curios on why this is happening. I will check it shortly.

**Comment by Achilles1515** [comment]
```ts
onDragStarted(event: KtdDragStart) {
      console.log("isInAngularZone: ", NgZone.isInAngularZone()); // outputs `true` on desktop, `false` on mobile
      this.isDragging = true;
    }
```

**Comment by llorenspujol** [comment]
I see that touch event from dragStart$ is outside the zone (which is expected) but it never re-enters. dragStarted event should be always inside the zone by default, and with that returning always 'true' in your test.

Do you want to do a Merge request with de fix? @Achilles1515 

Overall what needs to be done is ensure that the event dragStarted is inside the zone.

**Comment by llorenspujol** [comment]
I've fixed it since I want to include this bug solved into the next release with the scroll feature, here it is if you want to check: https://github.com/katoid/angular-grid-layout/commit/51d7d764b9dbff8bdb55ad87e4536c4eff805381

Thank you:)
