### ISSUE TITLE
Resize handle moves when content scrolls

### ISSUE THREAD

**Issue by PeterMDavies** [katoid/angular-grid-layout#30]
Hi,

Loving this component to enable us to have flexible dashboards in our app.  We have however discovered something I can find no solution for...

If the content of a tile needs to be scrolled, the resize handle moves with the content when scrolling, the result looks like this:
![image](https://user-images.githubusercontent.com/63111468/150518676-8ccfede6-6dd7-48f2-8d3e-593c209c726b.png)

Is this a bug or am I missing something?

Thanks,

-- Peter.

**Comment by llorenspujol** [comment]
I suspect that you are setting `overflow-y: auto` to the `<ktd-grid-item>`, making this way ktd-grid-item your scroll container. This makes position absolute from the resize handle to not work correctly, is true.

To solve it, I recommend you using an intermediate element to be your scroll container, for example:
```html
<ktd-grid-item>
      <!-- scroll container -->
     <div style="overflow-y: auto">
         <!-- your oveerflowing content here -->
     </div>
</ktd-grid-item>
```

Let me know if this fixed your issue!

**Comment by llorenspujol** [comment]
Yeah well, exactly exactly with this code doesn't work, is true. You need to set the scroll container width and height equal as it's parent `ktd-grid-item`:

```html
<ktd-grid-item>
      <!-- scroll container -->
     <div style="overflow-y: auto; width: 100%; height: 100%">
         <!-- your oveerflowing content here -->
     </div>
</ktd-grid-item>
```

If that doesn't solve your issue, you would need to reproduce it on stackblitz or somewhere similiar, and share it to me to see exactly what is going on.

**Comment by PeterMDavies** [comment]
Hi,

Thanks again.  it now works:
![image](https://user-images.githubusercontent.com/63111468/151189277-bce3f428-c0dd-4093-9e00-3afd9eeba260.png)

only slight annoyance now is that the handle is drawn over the scroll bar, any resolution for that?

Cheers,

-- Peter.

**Comment by llorenspujol** [comment]
Nice 👏 

Well, I see 3 possible ways:

- The first one (and easiest) would be overriding the styles of the resize item, that has the `class="grid-item-resize-icon"`, and set for example a different value on it's `right` style

- The second option is just add a little bit of padding on the `ktd-grid-item`, and, optionally, remove the border and maybe the background, thought it depends on the use case:

```html
<ktd-grid-item style="padding: 8px; box-sizing: border-box; background: transparent; border: none;">
      <!-- scroll container -->
     <div style="overflow-y: auto; width: 100%; height: 100%">
         <!-- your oveerflowing content here -->
     </div>
</ktd-grid-item>
```

- The third one would be just creating your custom handles, like it is on custom handles example:
https://katoid.github.io/angular-grid-layout/custom-handles

**Comment by PeterMDavies** [comment]
Hi,

Awesome - thanks for your help!

Option 2, but keeping the background and border:
![image](https://user-images.githubusercontent.com/63111468/151193768-e40d8542-0fad-45b4-af5d-ee55e67ac257.png)

we've enough to play with now.

Thanks again,

-- Peter.

**Comment by llorenspujol** [comment]
You are welcome!
