### ISSUE TITLE
Angular 13 peer dependency 

### ISSUE THREAD

**Issue by apauldev** [katoid/angular-grid-layout#31]
Hi while installing the package in a new Angular project I am getting-

`npm i @katoid/angular-grid-layout --save  `

`npm ERR! While resolving: syntese@0.0.0
npm ERR! Found: @angular/common@13.2.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.0.6" from @katoid/angular-grid-layout@0.2.0
npm ERR! node_modules/@katoid/angular-grid-layout
npm ERR!   @katoid/angular-grid-layout@"*" from the root project`

Is this the correct way to install this? Am I missing something?

**Comment by apauldev** [comment]
I was able to fix it by migrating to Yarn from NPM.
Other way to fix might be using an older version of Node (I tried but it didn't work).

**Comment by llorenspujol** [comment]
Hi @apauldev ! 
The version 0.2.0 of the lib has the angular peer dependencies fixed to angular 11:
```typescript
  "peerDependencies": {
      "@angular/common": "^11.0.6",
      "@angular/core": "^11.0.6"
  }
```
So the error may come from that. Said that, I was just expecting a warning like:
![image](https://user-images.githubusercontent.com/18361241/151934103-2a1c06df-0c96-4f48-aa66-320f3ba4775d.png)


Either way, soon will be released a new version of the Angular grid layout with Angular 12, that has peerDependencies:
```typescript
    "peerDependencies": {
        "@angular/common": ">=12.0.0",
        "@angular/core": ">=12.0.0"
    }
```
You could try it again with npm when this release is published.

It's nice you found a workaround although! 👍

**Comment by apauldev** [comment]
@llorenspujol  Thanks for getting back to me. Look forward to the progress you make. I will update here with NPM when the package updates. This way it will stay documented.

**Comment by llorenspujol** [comment]
@apauldev I have pushed the version 1.1.0 of the lib with the mentioned peerDependencies to >= 12.0.0, you can try with npm again and see if it shows that error. If you do, would be nice to receive feedback.
