### ISSUE TITLE
Upgrade to Angular v13

### ISSUE THREAD

**Issue by llorenspujol** [katoid/angular-grid-layout#36]
Upgrade from Angular v12 to Angular v13

Things to note:

1- See how move custom tslint-rules to eslint

2- See how we can ensure that a lib bundled with Angular v13 can **safely** have peerDependencies with a minor angular version, for example Angular v12. In theory, if we don't use any exclusive api feature of Angular v13, it should work with Angular v12.But Angular states this in their [documentation](https://angular.io/guide/creating-libraries#ensuring-library-version-compatibility):
> The Angular version used to build an application should always be the same or greater than the Angular versions used to build any of its dependent libraries. For example, if you had a library using Angular version 13, the application that depends on that library should use Angular version 13 or later. Angular does not support using an earlier version for the application.

We don't want now to cut support to Angular v12, so this is an important thing to study before upgrading.

PR (by @sheikalthaf): https://github.com/katoid/angular-grid-layout/pull/34

**Comment by llorenspujol** [comment]
@sheikalthaf thanks for you PR!

I created an issue to track down what is the impact of upgrading to Angular v13. What concerns me more, is that we don't want to cut support to Angular v12 users, because there is a lot of people using Angular v12 still. We need to investigate that before we proceed.

About the custom tslint rules, I would take car of that.

The PR now has conflicts, since I pushed some changes to 'main'. For now, I recommend not fixing the conflicts until we have ensured that with Angular 13 we would be able to specify peerDependencies to angular versions >= 12.0.0. when that is confirmed, we will proceed to upgrade to Angular v13. If you can do research, it would be nice, if not, I would do myself when possible.
Upgrading to Angular v13 is actually not a priority, since we upgraded to angular v12 last week. but, since you did a nice PR and took your time to upgrade it, if we can ensure support to Angular v12 users, we will proceed. Thanks!

**Comment by sheikalthaf** [comment]
@llorenspujol Thanks for the Angular 13 update issue tracker. I agree with your support for angular V12.

The main difference between angular V12 and V13 is their library compilation. Because In angular V13 libraries compiled to ivy fully (so we don't need to ngcc on npm install). Other than that their no difference between them.

Angular V13 is going to be 4 months old now so we need to support angular V13 also. If some developers using angular v12 means they can stick to the specific version which support angular V12. Something I'm following in my library.
![image](https://user-images.githubusercontent.com/22526247/153001941-9e28adf9-2cb0-4850-a505-7f23000ca693.png)

Thanks for this awesome library 🥳

**Comment by llorenspujol** [comment]
I have digged a little bit on it, and I have seen that a library built in Angular v13, can be compatible with Angular v12 setting this in tsconfig:
```json
    "angularCompilerOptions": {
        "compilationMode": "partial"
    }
```

So, we will have no problems about supporting angular v12 users

**Comment by llorenspujol** [comment]
@sheikalthaf Also, I have updated the PR https://github.com/katoid/angular-grid-layout/pull/34.  I have rebased it with `main` and made some changes. I commented he changes on the same PR, I also suggested the last steps that have to be made before finally merging it to the `main` branch. If there is any doubt you can tell me.

**Comment by llorenspujol** [comment]
Closed in https://github.com/katoid/angular-grid-layout/pull/49

**Comment by sheikalthaf** [comment]
@llorenspujol  when we can expect the release?

**Comment by llorenspujol** [comment]
@sheikalthaf My plan was when a new feature is added. Is there any specific reason you would like this release with Angular v13? If so, I could schedule.

**Comment by sheikalthaf** [comment]
@llorenspujol we have migrated most of the packages to angular v13 but this package is remaining in upgradation. So it is better we have the v13 supported version.

**Comment by llorenspujol** [comment]
@sheikalthaf I will try to publish this week, I will inform.

**Comment by sheikalthaf** [comment]
@llorenspujol Any update on this 🙄? Because now angular v14 also released.

**Comment by llorenspujol** [comment]
@sheikalthaf Yep sorry, I totally forgotten. Since there was no new features, just an upgrade from Angular v12 to Angular v13, publish seemed unnecessary. But my fault not doing it, since you requested and I said I would do it... and I didn't😅. Right now, If you can wait, would be nice to ship directly with Angular v14.

As I am digging into the breaking changes and deprecations, the upgrade seems straight forward without considering any refactoring of the new APIs that v14 brings. (That we may want to include in the near future).

**Comment by llorenspujol** [comment]
I created a new issue to track the Angular v14 update: https://github.com/katoid/angular-grid-layout/issues/54
