### ISSUE TITLE
Npm not available @katoid/angular-grid-layout@1.2.0.

### ISSUE THREAD

**Issue by DmitriyIvanko** [katoid/angular-grid-layout#37]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @katoid/angular-grid-layout@1.2.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by llorenspujol** [comment]
I am having no problems installing it, the version 1.2.0 is correctly published: https://www.npmjs.com/package/@katoid/angular-grid-layout

Is the error still present?

**Comment by DmitriyIvanko** [comment]
.npmrc problem, sorry
