### ISSUE TITLE
feature: Add CSS class for the dragged grid item animating back to it's placeholder location

### ISSUE THREAD

**Issue by Achilles1515** [katoid/angular-grid-layout#5]
Similar to the CDK drag-drop library's `cdk-drag-animating` class...

Classes should be added to the grid and grid items for each of their different "states" - one of these being the dragged item animating back to it's placeholder location after a pointer up event.

CDK drag/drop source for inspiration:
https://github.com/angular/components/blob/6eff9386b8145e4b3d50c59d353787d103d2fa8d/src/cdk/drag-drop/drag-ref.ts#L1011

**Comment by llorenspujol** [comment]
I agree we should have this feature to correctly solve the bug: https://github.com/katoid/angular-grid-layout/issues/6

The code from angular material is totally fine IMO. 
As I said in #6 , do you want to do a MR with the solution? Tell me if you need some kind of information.

**Comment by llorenspujol** [comment]
Closed in https://github.com/katoid/angular-grid-layout/pull/102
