### ISSUE TITLE
Set height to Fit the Screen Size 

### ISSUE THREAD

**Issue by AsjadMahmood** [katoid/angular-grid-layout#51]
I want the grid height to not exceed the screen size. in other words no scroll bar. So If i resize a certain grid item, it should not exceed the screen size.
I thought of disabling resize but i do want the resize to happen within certain area. 
thanks

**Comment by llorenspujol** [comment]
Seems exactly the definition of this issue: https://github.com/katoid/angular-grid-layout/issues/1

If so, close this issue and up vote the other one, and add some comments if needed. This way then issue gets more attention and is more probable to be done. Thanks!

**Comment by llorenspujol** [comment]
Closed in #69 . It would be available on the the published version
