### ISSUE TITLE
Upgrade to angular v14

### ISSUE THREAD

**Issue by llorenspujol** [katoid/angular-grid-layout#54]

**Comment by sheikalthaf** [comment]
@llorenspujol That's really great 👍🏻. Are you working on the update? If not shall I work on that

**Comment by sheikalthaf** [comment]
@llorenspujol  I'll check and raise a PR

**Comment by llorenspujol** [comment]
I added a commit that should be squashed to yours. When done, I will accept it and publish a new npm version.
