### ISSUE TITLE
Option to add vertical scroll with an external button

### ISSUE THREAD

**Issue by pau-garrido** [katoid/angular-grid-layout#58]
Hey, 

Right now the grid only adds scroll when you add an object on the bottom so it needs to grow.
What about an option where the grid doesn't need objects to grow so you can add scroll with a button (for example) and then fill this space with the objects that you want?

Regards,

**Comment by llorenspujol** [comment]
Hey @pau-garrido ,

If I understood well, you want to set the height of the grid yourself manually?
Which is your use case? You are using a non vertical compact position? Just for understanding the necessity of this feature, thanks!

**Comment by pau-garrido** [comment]
Hey @llorenspujol thanks for your answer.

Yes, I basically want the grid to occupy all the height I have on the display and also be able to add more height so it creates scroll in there (independently of the objects that I have on the grid). I guess that with an input that sets the height my problem would be solved.

**Comment by llorenspujol** [comment]
In PR #69 it has been added the option to add the height to the grid with an Input, so this issue should be solved. It would be available in the next published version.

**Comment by pau-garrido** [comment]
Thanks!
