### ISSUE TITLE
Max Height bug?

### ISSUE THREAD

**Issue by Rlima2** [katoid/angular-grid-layout#72]
Hi

How can i prevent this from happen?

There is no real way of use a fixed height?

Thanks a lot for your work

https://user-images.githubusercontent.com/52711677/212105727-cdd9ff27-34c3-4f90-8566-a74befe45982.mp4

**Comment by Rubiniuz** [comment]
so this is from an earlier bug report. this is actually an intended feature from what I read.
what you can do, however. is give the grid a max height. then set the overflow-y to scroll. and just hide the scrollbar.
you can then scroll within the grid when items go out of bounds. but you wont notice visually that you can scroll

**Comment by Rlima2** [comment]
Thanks a lot, i will work with that.
I will create another issue about other thing if you can help with that i will thank you a lot
https://github.com/katoid/angular-grid-layout/issues/74

**Comment by Rlima2** [comment]
I
