### ISSUE TITLE
It's possible to show the possible grid all the time?

### ISSUE THREAD

**Issue by Rlima2** [katoid/angular-grid-layout#74]
I fork the project, but i'm a newbie, there is some easy way to create a border in the possible placeholders?
I will have the same size in every item.

![Screenshot_3](https://user-images.githubusercontent.com/52711677/212141002-c5a8913a-837c-4c5f-94fa-166379b7a076.png)

**Comment by llorenspujol** [comment]
It is not supported in the lib, but there are workarounds to achieve it.

One easy way to do it, not the cleanest, is drawing another grid in the bottom of this one, with full of elements, one element for cell, and draw a border on them, this will simulate each possible placeholder.

I may consider implement this feature BTW, is simple and I understand in some cases would be nice to have.

**Comment by arnoudb** [comment]
@llorenspujol I would go for a different approach: css It is quite powerful hese days. Drawing the grid in one layer is much cheaper. This becomes more important for big and fine grained grids. 

I'll make a prototype that you can check

**Comment by arnoudb** [comment]
@Rlima2 I created aPR for this, hope its helpful!

**Comment by llorenspujol** [comment]
Closing this issue since this grid background feature is implemented!
