### ISSUE TITLE
Turn off drag and resize feature

### ISSUE THREAD

**Issue by monis01** [katoid/angular-grid-layout#89]
**Question:** Is there any way in current release to turn of drag and resize feature ?

**Requirement:** When dashboard is in edit mode than only items can be dragged and resized and when layout is finalized user can save that layout and not able to drag and resize again.

P.S. : 
In TODO features it's mentioned `Grid support for static grid items.`  is this same for disabling drag and resize ?

**Comment by llorenspujol** [comment]
Yes, you have two flags to enable/disable dragging and resizing for each grid item:

```html
<ktd-grid [cols]="cols"
          [rowHeight]="rowHeight"
          [layout]="layout"
          (layoutUpdated)="onLayoutUpdated($event)">
    <ktd-grid-item *ngFor="let item of layout; trackBy:trackById"
                         [id]="item.id"
                         [draggable]="!disableDrag"
                         [resizable]="!disableResize">

    </ktd-grid-item>
</ktd-grid>
```
You can see it also on the [playground example](https://katoid.github.io/angular-grid-layout/playground)
