### ISSUE TITLE
Support for Angular 16?

### ISSUE THREAD

**Issue by pjc2007** [katoid/angular-grid-layout#93]
Hi, I was looking at upgrading my application to Angular **16**, but I see in the package.json this is still at Angular **14**.

Would there be plans to add support for Angular 16?

**Comment by llorenspujol** [comment]
Hi!!
Even though the latest version of the library (v2.1.0) is written in Angular v14, it is completely compatible with Angular v16.

I'm closing the issue for now. If you experience any trouble, please feel free to open another issue. But as I mentioned, it should be working fine!
